import type { AnnotationData } from '@/types'

interface SummaryContext {
  prUrl: string
  owner: string
  repo: string
  prNumber: number
  branch: string
  title: string | null
  annotations: AnnotationData[]
  approvedFiles: string[]
}

export function generatePRDescription(ctx: SummaryContext): string {
  const { prUrl, owner, repo, prNumber, branch, title, annotations, approvedFiles } = ctx

  // Aggregate stats
  const total = annotations.length
  const byStatus = {
    open: annotations.filter((a) => a.status === 'open'),
    done: annotations.filter((a) => a.status === 'done'),
    resolved: annotations.filter((a) => a.status === 'resolved'),
    wontfix: annotations.filter((a) => a.status === 'wontfix'),
  }

  // Group by file
  const byFile = new Map<string, AnnotationData[]>()
  for (const a of annotations) {
    const list = byFile.get(a.filePath) ?? []
    list.push(a)
    byFile.set(a.filePath, list)
  }

  // Collect unique reviewers
  const reviewers = Array.from(
    new Set(annotations.map((a) => a.reviewer.name).filter(Boolean) as string[])
  )

  // Detect locales
  const locales = Array.from(
    new Set(
      annotations
        .map((a) => a.filePath.match(/content\/docs\/(\w+)\//)?.[1])
        .filter(Boolean) as string[]
    )
  )

  // Build markdown
  const lines: string[] = []

  lines.push('# Documentation Review Summary')
  lines.push('')

  // Overview
  lines.push('## Overview')
  lines.push('')
  lines.push(`- **Source PR**: [${owner}/${repo}#${prNumber}](${prUrl})`)
  if (title) lines.push(`- **Title**: ${title}`)
  lines.push(`- **Branch**: \`${branch}\``)
  if (reviewers.length) {
    lines.push(`- **Reviewers**: ${reviewers.map((r) => `@${r}`).join(', ')}`)
  }
  if (locales.length) {
    lines.push(`- **Locales**: ${locales.map((l) => `\`${l}\``).join(', ')}`)
  }
  lines.push('')

  // Stats
  lines.push('## Annotation Stats')
  lines.push('')
  lines.push('| Status | Count |')
  lines.push('|--------|-------|')
  lines.push(`| Total | ${total} |`)
  lines.push(`| ✅ Addressed (Done) | ${byStatus.done.length} |`)
  lines.push(`| ✔️ Confirmed (Resolved) | ${byStatus.resolved.length} |`)
  lines.push(`| 🟡 Open | ${byStatus.open.length} |`)
  lines.push(`| ❌ Won't Fix | ${byStatus.wontfix.length} |`)
  lines.push('')

  // Changes per file
  if (byFile.size > 0) {
    lines.push('## Changes by File')
    lines.push('')

    for (const [filePath, fileAnnotations] of byFile) {
      lines.push(`### \`${filePath}\``)
      lines.push('')

      const fileByStatus = {
        done: fileAnnotations.filter((a) => a.status === 'done'),
        resolved: fileAnnotations.filter((a) => a.status === 'resolved'),
        open: fileAnnotations.filter((a) => a.status === 'open'),
        wontfix: fileAnnotations.filter((a) => a.status === 'wontfix'),
      }

      // Addressed (done + resolved)
      const addressed = [...fileByStatus.resolved, ...fileByStatus.done]
      if (addressed.length) {
        lines.push(`**Addressed (${addressed.length})**:`)
        lines.push('')
        addressed.forEach((a, i) => {
          const statusIcon = a.status === 'resolved' ? '✔️' : '✅'
          const location = a.sourceLine ? ` [L${a.sourceLine}]` : ''
          const quote = a.selectedText ? ` — \`${truncate(a.selectedText, 60)}\`` : ''
          lines.push(`${i + 1}. ${statusIcon}${location}${quote}`)
          lines.push(`   > ${formatComment(a.comment)}`)
        })
        lines.push('')
      }

      // Won't fix
      if (fileByStatus.wontfix.length) {
        lines.push(`**Won't fix (${fileByStatus.wontfix.length})**:`)
        lines.push('')
        fileByStatus.wontfix.forEach((a, i) => {
          const location = a.sourceLine ? ` [L${a.sourceLine}]` : ''
          const quote = a.selectedText ? ` — \`${truncate(a.selectedText, 60)}\`` : ''
          lines.push(`${i + 1}. ❌${location}${quote}`)
          lines.push(`   > ${formatComment(a.comment)}`)
        })
        lines.push('')
      }

      // Still open
      if (fileByStatus.open.length) {
        lines.push(`**Still open (${fileByStatus.open.length})**:`)
        lines.push('')
        fileByStatus.open.forEach((a, i) => {
          const location = a.sourceLine ? ` [L${a.sourceLine}]` : ''
          const quote = a.selectedText ? ` — \`${truncate(a.selectedText, 60)}\`` : ''
          lines.push(`${i + 1}. 🟡${location}${quote}`)
          lines.push(`   > ${formatComment(a.comment)}`)
        })
        lines.push('')
      }
    }
  }

  // Approved changes (committed)
  if (approvedFiles.length > 0) {
    lines.push('## Committed Files')
    lines.push('')
    approvedFiles.forEach((f) => lines.push(`- \`${f}\``))
    lines.push('')
  }

  // Footer
  lines.push('---')
  lines.push('')
  lines.push('*Generated by [Cherry Docs Reviewer](https://github.com/jenelle/cherry-docs-reviewer)*')

  return lines.join('\n')
}

function truncate(str: string, n: number): string {
  const s = str.replace(/\s+/g, ' ').trim()
  return s.length > n ? s.slice(0, n) + '…' : s
}

function formatComment(comment: string): string {
  return comment.replace(/\n/g, '\n   > ').trim()
}
